// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001
#define ED_TITLU  4001
#define ED_MSG  4002
#define SL_ICON  4003
#define SL_BTNS  4004
#define CHK_HELP  4009
